### ISSUE TITLE
where is the minimongo?

### ISSUE THREAD

**Issue by yz89** [JohnnyCrazy/DDPClient-NET#1]
@JohnnyCrazy 
Tanks for your awesome job !  

I have some questions need your help. 
1. Is there have some local storage like minimongo to store the data which subscribe from server？ 
2. How can I find the local data? 
3. If I should maintain local data manual by the function `TaskSubscriber:Added() ... Changed()`

:)

**Comment by JohnnyCrazy** [comment]
Hi,

This library is just implementing the protocol, nothing more.
So if you want a local datastorage, you will need to implement it via the provided `Added` and `Removed` callbacks. I guess you could simply use a `List<>` to store your data.

Make sure you listen to the data changes BEFORE subscribing to them, else data will get lost.

**Comment by yz89** [comment]
I see. Thank you for your help.  :+1: 

I found I can change the architecture. I process the data immediately when Added callback called , so 

>  just implementing the protocol 

is enough.
