### ISSUE TITLE
Iam trying to run this under .NET 4.0 but getting  (njubi warning)

### ISSUE THREAD

**Issue by rickard-505** [JohnnyCrazy/DDPClient-NET#2]
Severity    Code    Description Project File    Line    Suppression State
Error   CS0311  The type 'DdpClient.DdpMessage' cannot be used as type parameter 'TEventArgs' in the generic type or method 'EventHandler<TEventArgs>'. There is no implicit reference conversion from 'DdpClient.DdpMessage' to 'System.EventArgs'.    DDPClient   \DDPClient-NET-master\DDPClient-NET-master\DDPClient\DdpWebSocket.cs    15  Active

**Comment by JohnnyCrazy** [comment]
Hi, sorry for the late response.

.NET 4.0 still uses `where T : EventArgs` in the generic version of  `EventHandler<T>`.
.NET 4.5 removed this constraint, so best choice would be updating to .NET 4.5.

(If you really need 4.0 support, I guess you could add an inheritance to `EventArgs` inside `DdpMessage.cs`)
