### ISSUE TITLE
Subscription Issues

### ISSUE THREAD

**Issue by firrae** [JohnnyCrazy/DDPClient-NET#5]
Hi there,

Not sure if this is even still alive in any capacity but we were hoping this would work for our use case and it almost does. Logins and method calls work but subscriptions don't seem to at all. Is this an issue on our side that someone could help us with, or is this just the library being old and out of date?

Thanks,

Steve

**Comment by firrae** [comment]
We seem to have found the solution. I will look at making a PR for the documentation with my other dev and see if that can help anyone in the future.

**Comment by JohnnyCrazy** [comment]
@firrae I'm not using Meteor anymore, but I'm of course happy for PRS :+1:
